# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_gfunction <- function(bet, a, alp, the, mu, gam, lam, x, rho, pi) {
    .Call(`_MR_rcpp_gfunction`, bet, a, alp, the, mu, gam, lam, x, rho, pi)
}

rcpp_hello_world <- function() {
    .Call(`_MR_rcpp_hello_world`)
}

rcpp_hess_lambda <- function(bet, a, alp, the, mu, gam, lam, x, rho) {
    .Call(`_MR_rcpp_hess_lambda`, bet, a, alp, the, mu, gam, lam, x, rho)
}

rcpp_obj <- function(bet, a, alp, the, mu, gam, lam, x, rho, the0, inv_the, gam0, inv_gam) {
    .Call(`_MR_rcpp_obj`, bet, a, alp, the, mu, gam, lam, x, rho, the0, inv_the, gam0, inv_gam)
}

rcpp_obj_lambda <- function(bet, a, alp, the, mu, gam, lam, x, rho) {
    .Call(`_MR_rcpp_obj_lambda`, bet, a, alp, the, mu, gam, lam, x, rho)
}

rcpp_score <- function(bet, a, alp, the, mu, gam, lam, x, rho, the0, inv_the, gam0, inv_gam) {
    .Call(`_MR_rcpp_score`, bet, a, alp, the, mu, gam, lam, x, rho, the0, inv_the, gam0, inv_gam)
}

rcpp_score_lambda <- function(bet, a, alp, the, mu, gam, lam, x, rho) {
    .Call(`_MR_rcpp_score_lambda`, bet, a, alp, the, mu, gam, lam, x, rho)
}

