# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_gfunction <- function(alp, the, x) {
    .Call(`_MR_rcpp_gfunction`, alp, the, x)
}

rcpp_hello_world <- function() {
    .Call(`_MR_rcpp_hello_world`)
}

rcpp_hess_lambda <- function(bet, a, alp, the, mu, gam, lam, x, rho) {
    .Call(`_MR_rcpp_hess_lambda`, bet, a, alp, the, mu, gam, lam, x, rho)
}

rcpp_obj <- function(bet, alp, the, lam, the0, inv_the, pi, inv_pi, x) {
    .Call(`_MR_rcpp_obj`, bet, alp, the, lam, the0, inv_the, pi, inv_pi, x)
}

rcpp_obj_lambda <- function(bet, a, alp, the, mu, gam, lam, x, rho) {
    .Call(`_MR_rcpp_obj_lambda`, bet, a, alp, the, mu, gam, lam, x, rho)
}

rcpp_score <- function(bet, alp, the, lam, the0, inv_the, pi, inv_pi, x) {
    .Call(`_MR_rcpp_score`, bet, alp, the, lam, the0, inv_the, pi, inv_pi, x)
}

rcpp_score_lambda <- function(bet, a, alp, the, mu, gam, lam, x, rho) {
    .Call(`_MR_rcpp_score_lambda`, bet, a, alp, the, mu, gam, lam, x, rho)
}

